version: "3.8"
services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - HOST=0.0.0.0
      - PORT=3030
      - DATABASE=libraryDb
      - USERNAME=docker
      - PASSWORD=dockerf
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=docker
      - DB_PASSWORD=dockerf
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=redisuser
      - REDIS_DB=0
      - ENVIRONMENT=stage
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: libraryDb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: dockerf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
